- platform: generic_thermostat
  name: Living Dining Room AC
  unique_id: climate.living_dining_room_ac
  heater: switch.living_dining_room_ac_switch
  target_sensor: sensor.dining_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Eli's Room AC
  unique_id: climate.elis_room_ac
  heater: switch.elis_room_ac_switch
  target_sensor: sensor.elis_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Elena's Room AC
  unique_id: climate.elenas_room_ac
  heater: switch.elenas_room_ac_switch
  target_sensor: sensor.elenas_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5