- platform: template
  switches:
    dining_room_ac_switch:
      unique_id: switch.dining_room_ac_switch
      value_template: "{{ states('input_boolean.dining_room_ac_power') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.dining_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dining_room_ac_power
    
    elis_room_ac_switch:
      unique_id: switch.elis_room_ac_switch
      value_template: "{{ states('input_boolean.elis_room_ac_power') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elis_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elis_room_ac_power

    elenas_room_ac_switch:
      unique_id: switch.elenas_room_ac_switch
      value_template: "{{ states('input_boolean.elenas_room_ac_power') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elenas_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elenas_room_ac_power

    lights_auto_control:
      unique_id: switch.lights_auto_control
      value_template: "{{ states('input_boolean.lights_auto_control_enabled') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.lights_auto_control_enabled
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.lights_auto_control_enabled